import type { Trip, TripInput } from "./types"

// Seed data embedded directly
const seedTrips: Trip[] = [
  {
    id: "trip-1",
    name: "Tyrol",
    description: "",
    startDate: new Date("2023-08-25"),
    endDate: new Date("2023-08-31"),
    destinations: [
      {
        id: "d1-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d1-2",
        city: "Vienna",
        country: "Austria",
        latitude: 48.2082,
        longitude: 16.3738,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d1-3",
        city: "Innsbruck",
        country: "Austria",
        latitude: 47.2699,
        longitude: 11.3896,
        transportationType: "plane",
        order: 2,
      },
      {
        id: "d1-4",
        city: "Obern",
        country: "Austria",
        latitude: 47.2699,
        longitude: 11.3896,
        transportationType: "plane",
        order: 3,
      },
      {
        id: "d1-5",
        city: "Vienna",
        country: "Austria",
        latitude: 47.2699,
        longitude: 11.3896,
        transportationType: "plane",
        order: 4,
      },
      {
        id: "d1-6",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 5,
      },
    ],
    companions: ["Hamed"],
    expenses: { hotel: 400, food: 200, transportation: 600, entryFees: 0, other: 0 },
  },
  {
    id: "trip-2",
    name: "Barcelona",
    description: "Honeymoon trip",
    startDate: new Date("2023-12-04"),
    endDate: new Date("2023-12-07"),
    destinations: [
      {
        id: "d2-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d2-2",
        city: "Barcelona",
        country: "Spain",
        latitude: 41.3851,
        longitude: 2.1734,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d2-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 2,
      },
    ],
    companions: [],
    expenses: { hotel: 420.4, food: 275.45, transportation: 361.78, entryFees: 71, other: 41.4 },
  },
  {
    id: "trip-3",
    name: "Prague",
    description: "",
    startDate: new Date("2023-12-22"),
    endDate: new Date("2023-12-25"),
    destinations: [
      {
        id: "d3-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d3-2",
        city: "Prague",
        country: "Czech Republic",
        latitude: 50.0755,
        longitude: 14.4378,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d3-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 2,
      },
    ],
    companions: ["Hasan"],
    expenses: { hotel: 259.82, food: 287.17, transportation: 259.2, entryFees: 0, other: 0 },
  },
  {
    id: "trip-4",
    name: "South Europe",
    description: "South Europe trip with Porosha",
    startDate: new Date("2024-01-05"),
    endDate: new Date("2024-01-11"),
    destinations: [
      {
        id: "d4-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d4-2",
        city: "Venice",
        country: "Italy",
        latitude: 45.4408,
        longitude: 12.3155,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d4-3",
        city: "Rome",
        country: "Italy",
        latitude: 41.9028,
        longitude: 12.4964,
        transportationType: "train",
        order: 2,
      },
      {
        id: "d4-4",
        city: "Lisbon",
        country: "Portugal",
        latitude: 38.7223,
        longitude: -9.1393,
        transportationType: "plane",
        order: 3,
      },
      {
        id: "d4-5",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 4,
      },
    ],
    companions: ["Porosha"],
    expenses: { hotel: 253.49, food: 286.57, transportation: 351.88, entryFees: 0, other: 19.2 },
  },
  {
    id: "trip-5",
    name: "Budapest",
    description: "",
    startDate: new Date("2024-05-18"),
    endDate: new Date("2024-05-22"),
    destinations: [
      {
        id: "d5-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d5-2",
        city: "Budapest",
        country: "Hungary",
        latitude: 47.4979,
        longitude: 19.0402,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d5-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 2,
      },
    ],
    companions: ["Siavash", "Sadaf", "Hamed"],
    expenses: { hotel: 179.2, food: 363, transportation: 188.42, entryFees: 54, other: 82 },
  },
  {
    id: "trip-6",
    name: "Krakow",
    description: "",
    startDate: new Date("2024-08-08"),
    endDate: new Date("2024-08-11"),
    destinations: [
      {
        id: "d6-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d6-2",
        city: "Krakow",
        country: "Poland",
        latitude: 50.0647,
        longitude: 19.945,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d6-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 2,
      },
    ],
    companions: [],
    expenses: { hotel: 252.69, food: 209.49, transportation: 231.82, entryFees: 160, other: 20 },
  },
  {
    id: "trip-7",
    name: "Milan",
    description: "",
    startDate: new Date("2024-12-19"),
    endDate: new Date("2024-12-24"),
    destinations: [
      {
        id: "d7-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d7-2",
        city: "Milan",
        country: "Italy",
        latitude: 45.4642,
        longitude: 9.19,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d7-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 2,
      },
    ],
    companions: ["Siavash", "Sadaf"],
    expenses: { hotel: 420.26, food: 234.66, transportation: 396.03, entryFees: 0, other: 25.48 },
  },
  {
    id: "trip-8",
    name: "Poznan",
    description: "",
    startDate: new Date("2024-12-26"),
    endDate: new Date("2024-12-29"),
    destinations: [
      {
        id: "d8-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d8-2",
        city: "Poznan",
        country: "Poland",
        latitude: 52.4064,
        longitude: 16.9252,
        transportationType: "train",
        order: 1,
      },
      {
        id: "d8-3",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "train",
        order: 2,
      },
    ],
    companions: [],
    expenses: { hotel: 204.5, food: 126.52, transportation: 77.96, entryFees: 8.55, other: 34.67 },
  },
  {
    id: "trip-9",
    name: "The Netherlands",
    description: "",
    startDate: new Date("2024-12-31"),
    endDate: new Date("2025-01-06"),
    destinations: [
      {
        id: "d9-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 0,
      },
      {
        id: "d9-2",
        city: "Amsterdam",
        country: "Netherlands",
        latitude: 52.3676,
        longitude: 4.9041,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d9-3",
        city: "Amersfoort",
        country: "Netherlands",
        latitude: 52.1569,
        longitude: 5.3878,
        transportationType: "train",
        order: 2,
      },
      {
        id: "d9-4",
        city: "Rotterdam",
        country: "Netherlands",
        latitude: 51.9225,
        longitude: 4.4675,
        transportationType: "car",
        order: 3,
      },
      {
        id: "d9-5",
        city: "Amersfoort",
        country: "Netherlands",
        latitude: 52.1569,
        longitude: 5.3878,
        transportationType: "car",
        order: 4,
      },
      {
        id: "d9-6",
        city: "Rotterdam",
        country: "Netherlands",
        latitude: 51.9225,
        longitude: 4.4675,
        transportationType: "train",
        order: 5,
      },
      {
        id: "d9-7",
        city: "Den Haag",
        country: "Netherlands",
        latitude: 52.0705,
        longitude: 4.3007,
        transportationType: "train",
        order: 6,
      },
      {
        id: "d9-8",
        city: "Rotterdam",
        country: "Netherlands",
        latitude: 51.9225,
        longitude: 4.4675,
        transportationType: "train",
        order: 7,
      },
      {
        id: "d9-9",
        city: "Hoorn",
        country: "Netherlands",
        latitude: 52.3676,
        longitude: 4.9041,
        transportationType: "train",
        order: 8,
      },
      {
        id: "d9-10",
        city: "Amsterdam",
        country: "Netherlands",
        latitude: 52.3676,
        longitude: 4.9041,
        transportationType: "train",
        order: 9,
      },
      {
        id: "d9-11",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 10,
      },
    ],
    companions: [],
    expenses: { hotel: 0, food: 214.64, transportation: 617.18, entryFees: 54, other: 30.24 },
  },
  {
    id: "trip-10",
    name: "Rostock",
    description: "",
    startDate: new Date("2025-07-04"),
    endDate: new Date("2025-07-05"),
    destinations: [
      {
        id: "d10-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d10-2",
        city: "Rostock",
        country: "Germany",
        latitude: 54.0924,
        longitude: 12.0991,
        transportationType: "train",
        order: 1,
      },
      {
        id: "d10-3",
        city: "Warnemünde",
        country: "Germany",
        latitude: 54.3333,
        longitude: 12.0833,
        transportationType: "train",
        order: 2,
      },
      {
        id: "d10-4",
        city: "Rostock",
        country: "Germany",
        latitude: 54.0924,
        longitude: 12.0991,
        transportationType: "train",
        order: 3,
      },
      {
        id: "d10-5",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "train",
        order: 4,
      },
    ],
    companions: [],
    expenses: { hotel: 313.5, food: 171.31, transportation: 159.96, entryFees: 46, other: 5 },
  },
  {
    id: "trip-11",
    name: "Malaga",
    description: "",
    startDate: new Date("2025-08-29"),
    endDate: new Date("2025-09-03"),
    destinations: [
      {
        id: "d11-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d11-2",
        city: "Malaga",
        country: "Spain",
        latitude: 36.7213,
        longitude: -4.4214,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d11-3",
        city: "Sevilla",
        country: "Spain",
        latitude: 36.7213,
        longitude: -4.4214,
        transportationType: "train",
        order: 2,
      },
      {
        id: "d11-4",
        city: "Malaga",
        country: "Spain",
        latitude: 36.7213,
        longitude: -4.4214,
        transportationType: "train",
        order: 3,
      },
      {
        id: "d11-5",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 4,
      },
    ],
    companions: [],
    expenses: { hotel: 442.37, food: 346.71, transportation: 662.19, entryFees: 113, other: 6 },
  },
  {
    id: "trip-12",
    name: "Vienna",
    description: "",
    startDate: new Date("2025-09-28"),
    endDate: new Date("2025-10-02"),
    destinations: [
      {
        id: "d12-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d12-2",
        city: "Vienna",
        country: "Austria",
        latitude: 48.2082,
        longitude: 16.3738,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d12-3",
        city: "Bratislava",
        country: "Slovakia",
        latitude: 48.1486,
        longitude: 17.1077,
        transportationType: "bus",
        order: 2,
      },
      {
        id: "d12-4",
        city: "Vienna",
        country: "Austria",
        latitude: 48.1486,
        longitude: 17.1077,
        transportationType: "bus",
        order: 3,
      },
      {
        id: "d12-5",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 4,
      },
    ],
    companions: [],
    expenses: { hotel: 299.2, food: 162.15, transportation: 464.79, entryFees: 44, other: 9.9 },
  },
  {
    id: "trip-13",
    name: "Canary Island Cruise",
    description: "",
    startDate: new Date("2025-12-13"),
    endDate: new Date("2025-12-22"),
    destinations: [
      {
        id: "d13-1",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: null,
        order: 0,
      },
      {
        id: "d13-2",
        city: "Marseille",
        country: "France",
        latitude: 43.2965,
        longitude: 5.3698,
        transportationType: "plane",
        order: 1,
      },
      {
        id: "d13-3",
        city: "Barcelona",
        country: "Spain",
        latitude: 41.3851,
        longitude: 2.1734,
        transportationType: "boat",
        order: 2,
      },
      {
        id: "d13-4",
        city: "Cadiz",
        country: "Spain",
        latitude: 36.5271,
        longitude: -6.2886,
        transportationType: "boat",
        order: 3,
      },
      {
        id: "d13-5",
        city: "Las Palmas de Gran Canaria",
        country: "Spain",
        latitude: 28.1235,
        longitude: -15.4363,
        transportationType: "boat",
        order: 4,
      },
      {
        id: "d13-6",
        city: "Berlin",
        country: "Germany",
        latitude: 52.52,
        longitude: 13.405,
        transportationType: "plane",
        order: 5,
      },
    ],
    companions: [],
    expenses: { hotel: 850, food: 622.74, transportation: 839.61, entryFees: 20, other: 52.45 },
  },
]

// In-memory store with singleton pattern
class TripStore {
  private trips: Trip[] = [...seedTrips]
  private static instance: TripStore

  static getInstance(): TripStore {
    if (!TripStore.instance) {
      TripStore.instance = new TripStore()
    }
    return TripStore.instance
  }

  getAll(): Trip[] {
    return [...this.trips].sort((a, b) => new Date(b.startDate).getTime() - new Date(a.startDate).getTime())
  }

  getById(id: string): Trip | null {
    return this.trips.find((t) => t.id === id) || null
  }

  create(input: TripInput): Trip {
    const id = input.id || `trip-${Date.now()}`
    const trip: Trip = {
      id,
      name: input.name,
      description: input.description,
      startDate: new Date(input.startDate),
      endDate: new Date(input.endDate),
      companions: input.companions,
      expenses: input.expenses,
      destinations: input.destinations.map((d, i) => ({
        id: `${id}-d${i}`,
        city: d.city,
        country: d.country,
        latitude: d.latitude,
        longitude: d.longitude,
        transportationType: d.transportationType,
        order: i,
      })),
    }
    this.trips.push(trip)
    return trip
  }

  update(id: string, input: TripInput): Trip | null {
    const index = this.trips.findIndex((t) => t.id === id)
    if (index === -1) return null

    const trip: Trip = {
      id,
      name: input.name,
      description: input.description,
      startDate: new Date(input.startDate),
      endDate: new Date(input.endDate),
      companions: input.companions,
      expenses: input.expenses,
      destinations: input.destinations.map((d, i) => ({
        id: `${id}-d${i}`,
        city: d.city,
        country: d.country,
        latitude: d.latitude,
        longitude: d.longitude,
        transportationType: d.transportationType,
        order: i,
      })),
    }
    this.trips[index] = trip
    return trip
  }

  delete(id: string): boolean {
    const index = this.trips.findIndex((t) => t.id === id)
    if (index === -1) return false
    this.trips.splice(index, 1)
    return true
  }
}

export const tripStore = TripStore.getInstance()
